import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "House Brain",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="bg-gray-100 dark:bg-gray-900 h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}

export default RootLayout;
